wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.35.2
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1711961517.635332
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 11
      - 49
      - 53
      - 55
      3:
      - 7
      - 13
      - 23
      4: 3.11.5
      5: 0.16.1
      6: 4.35.2
      8:
      - 2
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_mse_loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: test_mse_loss
      5: 1
      6:
      - 1
dim_A:
  desc: null
  value: 4
dim_X:
  desc: null
  value: 0
dim_Y:
  desc: null
  value: 1
dim_V:
  desc: null
  value: 1
seq_hidden_units:
  desc: null
  value: 16
num_heads:
  desc: null
  value: 2
head_size:
  desc: null
  value: null
dropout_rate:
  desc: null
  value: 0.1
num_layer:
  desc: null
  value: 1
