wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1714407131.0
    t:
      1:
      - 1
      - 9
      - 11
      - 49
      - 55
      2:
      - 1
      - 9
      - 11
      - 49
      - 55
      3:
      - 7
      - 13
      - 23
      4: 3.12.2
      5: 0.16.6
      6: 4.38.2
      8:
      - 2
      - 4
      - 5
      13: darwin-arm64
    m:
    - 1: trainer/global_step
      6:
      - 3
dim_treatments:
  desc: null
  value: 2
dim_covariates:
  desc: null
  value: 7
dim_outcomes:
  desc: null
  value: 4
dim_statics:
  desc: null
  value: null
seq_hidden_units:
  desc: null
  value: 10
num_heads:
  desc: null
  value: 2
dropout_rate:
  desc: null
  value: 0.2
num_layer:
  desc: null
  value: 3
timestep:
  desc: null
  value: 99
